# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-04 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill_senpai', '0002_auto_20181204_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='credits',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='lecture_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='nevents',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='tutorial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lecture',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skill_senpai.Categorie'),
        ),
    ]
