# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-04 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill_senpai', '0003_auto_20181204_2134'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
    ]
