# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-06 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill_senpai', '0004_auto_20181204_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='lanagues',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skill_senpai.Language'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='preconditions',
            field=models.ManyToManyField(related_name='_lecture_preconditions_+', to='skill_senpai.Lecture'),
        ),
    ]
