# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-06 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_senpai', '0005_auto_20181206_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='preconditions',
            field=models.ManyToManyField(null=True, related_name='_lecture_preconditions_+', to='skill_senpai.Lecture'),
        ),
    ]
