# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-06 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_senpai', '0006_auto_20181206_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='preconditions',
            field=models.ManyToManyField(blank=True, related_name='_lecture_preconditions_+', to='skill_senpai.Lecture'),
        ),
    ]
