# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-06 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill_senpai', '0007_auto_20181206_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='lanagues',
            new_name='languages',
        ),
    ]
