# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-06 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_senpai', '0008_auto_20181206_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
