# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-06 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_senpai', '0009_lecture_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='short_description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
